TEAMS = {
    "Brazil": {
        "fifa_rank": 3,
        "world_cup_titles": 5,
        "recent_wc_results": ["2022: QF", "2018: QF", "2014: 4th", "2010: QF", "2006: QF"],
        "style": "Attacking, technical, samba football",
        "star_players": ["Vinicius Jr.", "Rodrygo", "Raphinha", "Alisson"],
        "strengths": ["Attacking flair", "Individual brilliance", "Squad depth"],
        "weaknesses": ["Inconsistency under pressure", "Defensive organization"],
    },
    "France": {
        "fifa_rank": 2,
        "world_cup_titles": 2,
        "recent_wc_results": ["2022: Runner-up", "2018: Champion", "2014: QF", "2010: Group Stage"],
        "style": "Balanced, physically strong, counter-attacking",
        "star_players": ["Kylian Mbappé", "Antoine Griezmann", "Aurélien Tchouaméni"],
        "strengths": ["World-class striker", "Solid defense", "Experience"],
        "weaknesses": ["Internal team dynamics", "Consistency in group stage"],
    },
    "Argentina": {
        "fifa_rank": 1,
        "world_cup_titles": 3,
        "recent_wc_results": ["2022: Champion", "2018: R16", "2014: Runner-up", "2010: QF"],
        "style": "Organized, hard to beat, Messi-inspired",
        "star_players": ["Lautaro Martínez", "Julián Álvarez", "Rodrigo De Paul"],
        "strengths": ["Team cohesion", "Big game experience", "Defensive solidity"],
        "weaknesses": ["Post-Messi era transition", "Aging squad"],
    },
    "England": {
        "fifa_rank": 5,
        "world_cup_titles": 1,
        "recent_wc_results": ["2022: QF", "2018: 4th", "2014: Group Stage", "2010: R16"],
        "style": "Pressing, direct play, physical",
        "star_players": ["Jude Bellingham", "Harry Kane", "Phil Foden", "Bukayo Saka"],
        "strengths": ["Young talented squad", "Premier League quality", "Set pieces"],
        "weaknesses": ["Historically underperforms at tournaments", "Penalty shootouts"],
    },
    "Spain": {
        "fifa_rank": 7,
        "world_cup_titles": 1,
        "recent_wc_results": ["2022: R16", "2018: R16", "2014: Group Stage", "2010: Champion"],
        "style": "Tiki-taka, possession-based, technical",
        "star_players": ["Pedri", "Gavi", "Rodri", "Lamine Yamal"],
        "strengths": ["Technical excellence", "Young core", "Pressing"],
        "weaknesses": ["Lack of clinical striker", "Inconsistency in big games"],
    },
    "Germany": {
        "fifa_rank": 15,
        "world_cup_titles": 4,
        "recent_wc_results": ["2022: Group Stage", "2018: Group Stage", "2014: Champion", "2010: 3rd"],
        "style": "Structured, efficient, disciplined",
        "star_players": ["Florian Wirtz", "Jamal Musiala", "Joshua Kimmich"],
        "strengths": ["Tactical discipline", "Home support (2024 Euros)", "Technical quality"],
        "weaknesses": ["Recent tournament failures", "Rebuilding phase"],
    },
    "Portugal": {
        "fifa_rank": 6,
        "world_cup_titles": 0,
        "recent_wc_results": ["2022: QF", "2018: R16", "2014: Group Stage", "2010: 3rd"],
        "style": "Physical, direct, relying on individual quality",
        "star_players": ["Cristiano Ronaldo", "Bruno Fernandes", "Bernardo Silva", "Rúben Dias"],
        "strengths": ["Experienced veterans", "Technical quality", "Goal-scoring record"],
        "weaknesses": ["Over-reliance on key players", "No World Cup title"],
    },
    "Netherlands": {
        "fifa_rank": 8,
        "world_cup_titles": 0,
        "recent_wc_results": ["2022: QF", "2018: Did not qualify", "2014: 3rd"],
        "style": "Total football tradition, organized, direct",
        "star_players": ["Virgil van Dijk", "Cody Gakpo", "Xavi Simons"],
        "strengths": ["Defensive strength", "Set pieces", "Team structure"],
        "weaknesses": ["Inconsistency in attack", "Mental fragility in semis"],
    },
    "Belgium": {
        "fifa_rank": 4,
        "world_cup_titles": 0,
        "recent_wc_results": ["2022: Group Stage", "2018: 3rd", "2014: QF"],
        "style": "Counter-attacking, individual quality",
        "star_players": ["Kevin De Bruyne", "Romelu Lukaku", "Thibaut Courtois"],
        "strengths": ["World-class individuals", "Experience"],
        "weaknesses": ["Aging golden generation", "Team chemistry issues"],
    },
    "Italy": {
        "fifa_rank": 9,
        "world_cup_titles": 4,
        "recent_wc_results": ["2022: Did not qualify", "2018: Did not qualify", "2014: Group Stage", "2010: Group Stage"],
        "style": "Defensive, tactical, organized",
        "star_players": ["Federico Chiesa", "Nicolo Barella", "Gianluigi Donnarumma"],
        "strengths": ["Defensive organization", "Tactical intelligence"],
        "weaknesses": ["Failure to qualify recently", "Lack of clinical striker"],
    },
    "Croatia": {
        "fifa_rank": 10,
        "world_cup_titles": 0,
        "recent_wc_results": ["2022: 3rd", "2018: Runner-up", "2014: Group Stage"],
        "style": "Compact, counter-attacking, technically skilled",
        "star_players": ["Luka Modric", "Ivan Perisic", "Mateo Kovacic"],
        "strengths": ["Midfield quality", "Tournament experience", "Mental strength"],
        "weaknesses": ["Aging key players", "Small nation depth"],
    },
    "Morocco": {
        "fifa_rank": 14,
        "world_cup_titles": 0,
        "recent_wc_results": ["2022: 4th (historic)", "2018: Group Stage", "2014: Did not qualify"],
        "style": "Organized defense, counter-attacking, physical",
        "star_players": ["Achraf Hakimi", "Hakim Ziyech", "Yassine Bounou"],
        "strengths": ["Exceptional defense", "Team spirit", "Tournament experience"],
        "weaknesses": ["Limited attacking creativity", "Dependence on key players"],
    },
    "Japan": {
        "fifa_rank": 16,
        "world_cup_titles": 0,
        "recent_wc_results": ["2022: R16", "2018: R16", "2014: Group Stage"],
        "style": "Disciplined, high pressing, technically sound",
        "star_players": ["Takumi Minamino", "Daichi Kamada", "Ritsu Doan"],
        "strengths": ["Work rate", "Discipline", "Ability to upset favorites"],
        "weaknesses": ["Physical disadvantage vs European/South American teams"],
    },
    "Senegal": {
        "fifa_rank": 20,
        "world_cup_titles": 0,
        "recent_wc_results": ["2022: R16", "2018: Did not qualify", "2014: Did not qualify"],
        "style": "Physical, direct, fast transitions",
        "star_players": ["Sadio Mané", "Édouard Mendy", "Idrissa Gueye"],
        "strengths": ["Physical prowess", "Individual quality", "Passionate play"],
        "weaknesses": ["Inconsistency", "Over-reliance on Mané"],
    },
    "USA": {
        "fifa_rank": 11,
        "world_cup_titles": 0,
        "recent_wc_results": ["2022: R16", "2018: Did not qualify", "2014: R16"],
        "style": "Athletic, energetic, improving tactically",
        "star_players": ["Christian Pulisic", "Weston McKennie", "Tyler Adams"],
        "strengths": ["Athletic ability", "Growing talent pool", "Home advantage (2026 host)"],
        "weaknesses": ["Lack of top-level tournament wins", "Inconsistent performances"],
    },
    "Mexico": {
        "fifa_rank": 13,
        "world_cup_titles": 0,
        "recent_wc_results": ["2022: Group Stage", "2018: R16", "2014: R16"],
        "style": "Technical, tactical, experienced",
        "star_players": ["Hirving Lozano", "Raúl Jiménez", "Guillermo Ochoa"],
        "strengths": ["Experienced players", "Tactical organization"],
        "weaknesses": ["Notorious R16 curse (7 consecutive exits in R16)"],
    },
    "Australia": {
        "fifa_rank": 24,
        "world_cup_titles": 0,
        "recent_wc_results": ["2022: QF", "2018: Group Stage", "2014: Group Stage"],
        "style": "Physical, direct, team-oriented",
        "star_players": ["Mathew Leckie", "Mitchell Duke", "Ryan"],
        "strengths": ["Fighting spirit", "Ability to upset bigger teams"],
        "weaknesses": ["Limited individual quality at top level"],
    },
    "South Korea": {
        "fifa_rank": 23,
        "world_cup_titles": 0,
        "recent_wc_results": ["2022: R16", "2018: Group Stage", "2014: Group Stage"],
        "style": "High intensity, disciplined, organized",
        "star_players": ["Son Heung-min", "Kim Min-jae", "Lee Jae-sung"],
        "strengths": ["Work rate", "Son's quality", "Defensive organization"],
        "weaknesses": ["Over-reliance on Son", "Inconsistency away from home"],
    },
    "Iran": {
        "fifa_rank": 22,
        "world_cup_titles": 0,
        "recent_wc_results": ["2022: Group Stage", "2018: Group Stage", "2014: Group Stage"],
        "style": "Defensive, organized, disciplined",
        "star_players": ["Mehdi Taremi", "Sardar Azmoun"],
        "strengths": ["Defensive solidity", "Team discipline"],
        "weaknesses": ["Limited attacking quality", "Rarely advance past group stage"],
    },
    "Canada": {
        "fifa_rank": 43,
        "world_cup_titles": 0,
        "recent_wc_results": ["2022: Group Stage (first WC since 1986)", "2026: Co-host"],
        "style": "Physical, improving rapidly",
        "star_players": ["Alphonso Davies", "Jonathan David", "Cyle Larin"],
        "strengths": ["Athletic ability", "Davies' pace and quality"],
        "weaknesses": ["Inexperience at top level", "Inconsistency"],
    },
}

def get_team_list():
    return sorted(TEAMS.keys())

def get_team_data(team_name: str):
    return TEAMS.get(team_name)
